### ISSUE TITLE
Make glium_graphics window backend agnostic.

### ISSUE THREAD

**Issue by Potpourri** [PistonDevelopers/glium_graphics#29]
* [x] Add `OpenGLWindow` trait with these methods(`get_proc_address`, `is_current`, `make_current`) to `window` crate -- issue PistonDevelopers/window#44, PR PistonDevelopers/window#45
* [ ] Impl glium `Backend` trait for `T: OpenGLWindow` and add fn to create context -- PR #30
* [x] Impl `OpenGLWindow` in window backends:
      * [x] glutin_window -- PR PistonDevelopers/glutin_window#19
      * [x] glfw_window -- PR PistonDevelopers/glfw_window#97
      * [x] sdl2_window -- PR PistonDevelopers/sdl2_window#151

**Comment by bvssvni** [comment]
`get_proc_address` is it used for OpenGL.

**Comment by bvssvni** [comment]
Could rename `Context` to `OpenGLWindow`.

**Comment by Potpourri** [comment]
I agree.

**Comment by bvssvni** [comment]
I opened https://github.com/PistonDevelopers/window/issues/44
